name: Health Check

on: push

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: URL Health Check
        uses: Jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-zct8.onrender.com/not-health
          max-attempts: 3
          retry-delay: 6s

  health_check_log:
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps:
      - name: Log failure if health check fails
        run: echo "Health check failed $(date '+%d.%m.%Y %H:%M')" >> health_check.log

      - name: Store health-check log
        uses: actions/upload-artifact@v4
        with:
          name: health-check-log
          path: health-check.log
